language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
#   WORKAROUND FOR: https://github.com/ansible/ansible/issues/31741
    - pip install --upgrade setuptools
#   END OF WORKAROUND
    - pip install -r requirements-tests.txt
    - pip install  .
script: make test
