---
inputs:
  - name: leapp_root 
    type: BaseTypeString
  
  - name: container_name 
    type: BaseTypeString


executor:
  type: bash
  arguments:
    - "@leapp_root.value@"
    - "@container_name.value@"
  payload: |
    LEAPP_ROOT=$1
    CONTAINER_NAME=$2
   
    cd $LEAPP_ROOT/$CONTAINER_NAME

    # Move hosts, so it can be used in docker 
    mv etc/hosts /etc/hosts.source
    ln -s etc/hosts.source etc/hosts
